export { default as Header } from './Header'
export { default as About } from './pages/About'
export { default as Projects } from './pages/Projects'
export { default as Contact } from './pages/Contact'
export { default as Photography } from './pages/Photography'
export { default as Footer } from './Footer'
export { default as Main } from './Main'
export { default as Project } from '../components/pages/templates/Project'